name: 'CI'

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install

      - name: Sort package.json
        run: |
          npm run ci:sort-package-json

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: sort package.json'
          push_options: --force

      - name: Format
        run: |
          npm run ci:format

      - name: Lint
        run: |
          npm run ci:lint

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: lint'
          push_options: --force

  TEST:
    needs: CI
    if: ${{ github.event_name == 'pull_request' && needs.CI.result == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Run Test with coverage
        run: npx vitest --coverage.enabled true

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          threshold-icons: "{0: 'ðŸ”´', 80: 'ðŸŸ ', 90: 'ðŸŸ¢'}"
